modLoader="javafml"
loaderVersion="[44,)"
license="https://github.com/willatendo/Willatendos-Licensing"
issueTrackerURL="https://github.com/willatendo/Missing-Links/issues"

[[mods]]
modId="missinglinks" 
version="4.1.0"
displayName="Missing Links"
updateJSONURL="https://github.com/willatendo/Missing-Links/raw/main/updates.json"
displayURL="https://github.com/willatendo/Missing-Links"
logoFile="missing_links_logo.png" 
authors="Willatendo"
description='''
Adds some weird oversites that Mojang forgot about!
'''

[[dependencies.missinglinks]] 
    modId="forge" 
    mandatory=true 
    versionRange="[44,)" 
    ordering="NONE"
    side="BOTH"
    
[[dependencies.missinglinks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"