modLoader="javafml"
loaderVersion="[41,)"
license="Custom"
issueTrackerURL="https://github.com/willatendo/Missing-Links/issues"

[[mods]]
modId="missinglinks" 
version="3.0.0"
displayName="Missing Links"
updateJSONURL="https://github.com/willatendo/Missing-Links/raw/main/updates.json"
displayURL="https://github.com/willatendo/Missing-Links"
logoFile="missing_links_logo.png" 
authors="Willatendo"
description='''
Adds some weird oversites that Mojang forgot about!
'''

[[dependencies.missinglinks]] 
    modId="forge" 
    mandatory=true 
    versionRange="[41,)" 
    ordering="NONE"
    side="BOTH"
    
[[dependencies.missinglinks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"