package missinglinks;

import com.tterrag.registrate.util.nullness.NonNullSupplier;

import missinglinks.data.MissingLinksTranslationLanguageProvider;
import missinglinks.server.block.MissingLinksBlocks;
import missinglinks.server.util.MissingLinksRegistrate;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.data.event.GatherDataEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;

@Mod(MissingLinksMod.ID)
public class MissingLinksMod {
	public static final String ID = "missinglinks";
	private static final NonNullSupplier<MissingLinksRegistrate> REGISTRATE = MissingLinksRegistrate.lazy(ID);

	public MissingLinksMod() {
		IEventBus iEventBus = FMLJavaModLoadingContext.get().getModEventBus();

		MissingLinksBlocks.init();

		iEventBus.addListener(this::dataSetup);
	}

	private void dataSetup(GatherDataEvent event) {
		DataGenerator dataGenerator = event.getGenerator();
		PackOutput packOutput = dataGenerator.getPackOutput();
		dataGenerator.addProvider(true, new MissingLinksTranslationLanguageProvider(packOutput, "sv_se", provider -> {
			provider.addBlock(MissingLinksBlocks.ANDESITE.blocks()[0], "Andesittryckplatta");
			provider.addBlock(MissingLinksBlocks.ANDESITE.blocks()[1], "Andesitknapp");
			provider.addBlock(MissingLinksBlocks.DIORITE.blocks()[0], "Diorittryckplatta");
			provider.addBlock(MissingLinksBlocks.DIORITE.blocks()[1], "Dioritknapp");
			provider.addBlock(MissingLinksBlocks.GRANITE.blocks()[0], "Granitetryckplatta");
			provider.addBlock(MissingLinksBlocks.GRANITE.blocks()[1], "Graniteknapp");
			provider.addBlock(MissingLinksBlocks.CALCITE_REDSTONE.blocks()[0], "Kalcitetryckplatta");
			provider.addBlock(MissingLinksBlocks.CALCITE_REDSTONE.blocks()[1], "Kalcitknapp");
			provider.addBlock(MissingLinksBlocks.TUFF_REDSTONE.blocks()[0], "Tufftryckplatta");
			provider.addBlock(MissingLinksBlocks.TUFF_REDSTONE.blocks()[1], "Tuffknapp");
			provider.addBlock(MissingLinksBlocks.DRIPSTONE_BLOCK_REDSTONE.blocks()[0], "Droppstenstryckplatta");
			provider.addBlock(MissingLinksBlocks.DRIPSTONE_BLOCK_REDSTONE.blocks()[1], "Droppstensknapp");
			provider.addBlock(MissingLinksBlocks.SMOOTH_BASALT_REDSTONE.blocks()[0], "Len basalttryckplatta");
			provider.addBlock(MissingLinksBlocks.SMOOTH_BASALT_REDSTONE.blocks()[1], "Len basaltknapp");
			provider.addBlock(MissingLinksBlocks.END_STONE_REDSTONE.blocks()[0], "Endstentryckplatta");
			provider.addBlock(MissingLinksBlocks.END_STONE_REDSTONE.blocks()[1], "Endstenknapp");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(0).blocks()[0], "Vit betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(0).blocks()[1], "Vit betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(0).blocks()[2], "Vit betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(1).blocks()[0], "Orange betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(1).blocks()[1], "Orange betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(1).blocks()[2], "Orange betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(2).blocks()[0], "Ljuslila betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(2).blocks()[1], "Ljuslila betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(2).blocks()[2], "Ljuslila betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(3).blocks()[0], "Ljusblå betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(3).blocks()[1], "Ljusblå betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(3).blocks()[2], "Ljusblå betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(4).blocks()[0], "Gul betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(4).blocks()[1], "Gul betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(4).blocks()[2], "Gul betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(5).blocks()[0], "Limegrön betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(5).blocks()[1], "Limegrön betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(5).blocks()[2], "Limegrön betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(6).blocks()[0], "Rosa betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(6).blocks()[1], "Rosa betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(6).blocks()[2], "Rosa betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(7).blocks()[0], "Grå betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(7).blocks()[1], "Grå betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(7).blocks()[2], "Grå betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(8).blocks()[0], "Ljusgrå betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(8).blocks()[1], "Ljusgrå betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(8).blocks()[2], "Ljusgrå betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(9).blocks()[0], "Turkos betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(9).blocks()[1], "Turkos betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(9).blocks()[2], "Turkos betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(10).blocks()[0], "Lila betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(10).blocks()[1], "Lila betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(10).blocks()[2], "Lila betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(11).blocks()[0], "Blå betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(11).blocks()[1], "Blå betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(11).blocks()[2], "Blå betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(12).blocks()[0], "Brun betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(12).blocks()[1], "Brun betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(12).blocks()[2], "Brun betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(13).blocks()[0], "Grön betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(13).blocks()[1], "Grön betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(13).blocks()[2], "Grön betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(14).blocks()[0], "Röd betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(14).blocks()[1], "Röd betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(14).blocks()[2], "Röd betongmur");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(15).blocks()[0], "Svart betongtrappa");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(15).blocks()[1], "Svart betongplatta");
			provider.addBlock(MissingLinksBlocks.CONCRETE.get(15).blocks()[2], "Svart betongmur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(0).blocks()[0], "Vit terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(0).blocks()[1], "Vit terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(0).blocks()[2], "Vit terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(1).blocks()[0], "Orange terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(1).blocks()[1], "Orange terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(1).blocks()[2], "Orange terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(2).blocks()[0], "Ljuslila terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(2).blocks()[1], "Ljuslila terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(2).blocks()[2], "Ljuslila terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(3).blocks()[0], "Ljusblå terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(3).blocks()[1], "Ljusblå terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(3).blocks()[2], "Ljusblå terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(4).blocks()[0], "Gul terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(4).blocks()[1], "Gul terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(4).blocks()[2], "Gul terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(5).blocks()[0], "Limegrön terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(5).blocks()[1], "Limegrön terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(5).blocks()[2], "Limegrön terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(6).blocks()[0], "Rosa terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(6).blocks()[1], "Rosa terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(6).blocks()[2], "Rosa terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(7).blocks()[0], "Grå terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(7).blocks()[1], "Grå terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(7).blocks()[2], "Grå terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(8).blocks()[0], "Ljusgrå terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(8).blocks()[1], "Ljusgrå terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(8).blocks()[2], "Ljusgrå terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(9).blocks()[0], "Turkos terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(9).blocks()[1], "Turkos terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(9).blocks()[2], "Turkos terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(10).blocks()[0], "Lila terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(10).blocks()[1], "Lila terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(10).blocks()[2], "Lila terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(11).blocks()[0], "Blå terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(11).blocks()[1], "Blå terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(11).blocks()[2], "Blå terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(12).blocks()[0], "Brun terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(12).blocks()[1], "Brun terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(12).blocks()[2], "Brun terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(13).blocks()[0], "Grön terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(13).blocks()[1], "Grön terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(13).blocks()[2], "Grön terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(14).blocks()[0], "Röd terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(14).blocks()[1], "Röd terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(14).blocks()[2], "Röd terrakottamur");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(15).blocks()[0], "Svart terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(15).blocks()[1], "Svart terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.TERRACOTTA.get(15).blocks()[2], "Svart terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(0).blocks()[0], "Vitglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(0).blocks()[1], "Vitglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(0).blocks()[2], "Vitglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(1).blocks()[0], "Orangeglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(1).blocks()[1], "Orangeglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(1).blocks()[2], "Orangeglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(2).blocks()[0], "Ljuslilaglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(2).blocks()[1], "Ljuslilaglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(2).blocks()[2], "Ljuslilaglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(3).blocks()[0], "Ljusblåglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(3).blocks()[1], "Ljusblåglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(3).blocks()[2], "Ljusblåglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(4).blocks()[0], "Gulglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(4).blocks()[1], "Gulglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(4).blocks()[2], "Gulglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(5).blocks()[0], "Limegrönglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(5).blocks()[1], "Limegrönglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(5).blocks()[2], "Limegrönglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(6).blocks()[0], "Rosaglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(6).blocks()[1], "Rosaglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(6).blocks()[2], "Rosaglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(7).blocks()[0], "Gråglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(7).blocks()[1], "Gråglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(7).blocks()[2], "Gråglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(8).blocks()[0], "Ljusgråglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(8).blocks()[1], "Ljusgråglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(8).blocks()[2], "Ljusgråglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(9).blocks()[0], "Turkosglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(9).blocks()[1], "Turkosglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(9).blocks()[2], "Turkosglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(10).blocks()[0], "Lilaglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(10).blocks()[1], "Lilaglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(10).blocks()[2], "Lilaglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(11).blocks()[0], "Blåglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(11).blocks()[1], "Blåglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(11).blocks()[2], "Blåglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(12).blocks()[0], "Brunglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(12).blocks()[1], "Brunglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(12).blocks()[2], "Brunglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(13).blocks()[0], "Grönglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(13).blocks()[1], "Grönglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(13).blocks()[2], "Grönglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(14).blocks()[0], "Rödglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(14).blocks()[1], "Rödglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(14).blocks()[2], "Rödglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(15).blocks()[0], "Svartglaserad terrakottatrappa");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(15).blocks()[1], "Svartglaserad terrakottaplatta");
			provider.addBlock(MissingLinksBlocks.GLAZED_TERRACOTTA.get(15).blocks()[2], "Svartglaserad terrakottamur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(0).blocks()[0], "Vit ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(0).blocks()[1], "Vit ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(0).blocks()[2], "Vit ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(1).blocks()[0], "Orange ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(1).blocks()[1], "Orange ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(1).blocks()[2], "Orange ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(2).blocks()[0], "Ljuslila ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(2).blocks()[1], "Ljuslila ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(2).blocks()[2], "Ljuslila ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(3).blocks()[0], "Ljusblå ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(3).blocks()[1], "Ljusblå ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(3).blocks()[2], "Ljusblå ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(4).blocks()[0], "Gul ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(4).blocks()[1], "Gul ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(4).blocks()[2], "Gul ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(5).blocks()[0], "Limegrön ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(5).blocks()[1], "Limegrön ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(5).blocks()[2], "Limegrön ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(6).blocks()[0], "Rosa ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(6).blocks()[1], "Rosa ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(6).blocks()[2], "Rosa ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(7).blocks()[0], "Grå ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(7).blocks()[1], "Grå ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(7).blocks()[2], "Grå ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(8).blocks()[0], "Ljusgrå ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(8).blocks()[1], "Ljusgrå ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(8).blocks()[2], "Ljusgrå ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(9).blocks()[0], "Turkos ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(9).blocks()[1], "Turkos ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(9).blocks()[2], "Turkos ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(10).blocks()[0], "Lila ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(10).blocks()[1], "Lila ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(10).blocks()[2], "Lila ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(11).blocks()[0], "Blå ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(11).blocks()[1], "Blå ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(11).blocks()[2], "Blå ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(12).blocks()[0], "Brun ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(12).blocks()[1], "Brun ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(12).blocks()[2], "Brun ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(13).blocks()[0], "Grön ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(13).blocks()[1], "Grön ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(13).blocks()[2], "Grön ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(14).blocks()[0], "Röd ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(14).blocks()[1], "Röd ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(14).blocks()[2], "Röd ullmur");
			provider.addBlock(MissingLinksBlocks.WOOL.get(15).blocks()[0], "Svart ulltrappa");
			provider.addBlock(MissingLinksBlocks.WOOL.get(15).blocks()[1], "Svart ullplatta");
			provider.addBlock(MissingLinksBlocks.WOOL.get(15).blocks()[2], "Svart ullmur");
			provider.addBlock(MissingLinksBlocks.CALCITE.blocks()[0], "Kalcittrappa");
			provider.addBlock(MissingLinksBlocks.CALCITE.blocks()[1], "Kalcitplatta");
			provider.addBlock(MissingLinksBlocks.CALCITE.blocks()[2], "Kalcitmur");
			provider.addBlock(MissingLinksBlocks.TUFF.blocks()[0], "Tufftrappa");
			provider.addBlock(MissingLinksBlocks.TUFF.blocks()[1], "Tuffplatta");
			provider.addBlock(MissingLinksBlocks.TUFF.blocks()[2], "Tuffmur");
			provider.addBlock(MissingLinksBlocks.DRIPSTONE_BLOCK.blocks()[0], "Droppstenstrappa");
			provider.addBlock(MissingLinksBlocks.DRIPSTONE_BLOCK.blocks()[1], "Droppstensplatta");
			provider.addBlock(MissingLinksBlocks.DRIPSTONE_BLOCK.blocks()[2], "Droppstensmur");
			provider.addBlock(MissingLinksBlocks.SMOOTH_BASALT.blocks()[0], "Len basalttrappa");
			provider.addBlock(MissingLinksBlocks.SMOOTH_BASALT.blocks()[1], "Len basaltplatta");
			provider.addBlock(MissingLinksBlocks.SMOOTH_BASALT.blocks()[2], "Len basaltmur");
			provider.addBlock(MissingLinksBlocks.END_STONE.blocks()[0], "Endstentrappa");
			provider.addBlock(MissingLinksBlocks.END_STONE.blocks()[1], "Endstenplatta");
			provider.addBlock(MissingLinksBlocks.END_STONE.blocks()[2], "Endstenmur");
			provider.addBlock(MissingLinksBlocks.OBSIDIAN.blocks()[0], "Obsidiantrappa");
			provider.addBlock(MissingLinksBlocks.OBSIDIAN.blocks()[1], "Obsidianplatta");
			provider.addBlock(MissingLinksBlocks.OBSIDIAN.blocks()[2], "Obsidianmur");
			provider.addBlock(MissingLinksBlocks.CRYING_OBSIDIAN.blocks()[0], "Gråtande obsidiantrappa");
			provider.addBlock(MissingLinksBlocks.CRYING_OBSIDIAN.blocks()[1], "Gråtande obsidianplatta");
			provider.addBlock(MissingLinksBlocks.CRYING_OBSIDIAN.blocks()[2], "Gråtande obsidianmur");
			provider.addBlock(MissingLinksBlocks.QUARTZ_BRICKS.blocks()[0], "Kvartsmurstentrappa");
			provider.addBlock(MissingLinksBlocks.QUARTZ_BRICKS.blocks()[1], "Kvartsmurstenplatta");
			provider.addBlock(MissingLinksBlocks.QUARTZ_BRICKS.blocks()[2], "Kvartsmurstenmur");
			provider.addBlock(MissingLinksBlocks.QUARTZ_BLOCK.blocks()[0], "Kvartsmur");
			provider.addBlock(MissingLinksBlocks.SMOOTH_QUARTZ.blocks()[0], "Len kvartsmur");
			provider.addBlock(MissingLinksBlocks.SMOOTH_SANDSTONE.blocks()[0], "Len sandstenssmur");
			provider.addBlock(MissingLinksBlocks.SMOOTH_RED_SANDSTONE.blocks()[0], "Len röd sandstenssmur");
			provider.addBlock(MissingLinksBlocks.SMOOTH_STONE.blocks()[0], "Len stentrappa");
			provider.addBlock(MissingLinksBlocks.SMOOTH_STONE.blocks()[1], "Len stenmur");
			provider.addBlock(MissingLinksBlocks.RED_NETHER_BRICKS.blocks()[0], "Röd nethertaket");
			provider.addBlock(MissingLinksBlocks.RED_NETHER_BRICKS.blocks()[1], "Röd nethergrind");
			provider.addBlock(MissingLinksBlocks.NETHER_BRICKS.blocks()[0], "Nethergrind");
			provider.addBlock(MissingLinksBlocks.PACKED_MUDS.blocks()[0], "Packad gyttjatrappa");
			provider.addBlock(MissingLinksBlocks.PACKED_MUDS.blocks()[1], "Packad gyttjaplatta");
			provider.addBlock(MissingLinksBlocks.PACKED_MUDS.blocks()[2], "Packad gyttjamur");
			provider.addBlock(MissingLinksBlocks.SCULKS.blocks()[0], "Sculktrappa");
			provider.addBlock(MissingLinksBlocks.SCULKS.blocks()[1], "Sculkplatta");
			provider.addBlock(MissingLinksBlocks.SCULKS.blocks()[2], "Sculkmur");
		}));
	}

	public static MissingLinksRegistrate getRegistrate() {
		return REGISTRATE.get();
	}

	public static ResourceLocation rL(String path) {
		return new ResourceLocation(ID, path);
	}
}
